name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test

  create-release:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Install dependencies
      run: npm install
    
    - name: Configure git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    
    - name: Create release with release-it
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version="${{ inputs.version }}"
        # Remove 'v' prefix if present for release-it
        clean_version=${version#v}
        echo "Creating release for version: $clean_version"
        
        # Use release-it to handle version bump, commit, tag, and changelog
        npx release-it $clean_version --ci

  create-rc-build:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
          
    - name: Deploy to RC
      run: |
        echo "Release build is ready"

  deploy-beta:
    runs-on: ubuntu-latest
    needs: create-rc-build
    environment: beta
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        
    - name: Install dependencies
      run: npm install
      
    - name: Deploy to Beta
      run: |
        echo "Deploying version ${{ inputs.version }} to beta environment..."
        echo "Application deployed to beta"

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-beta
    environment: production
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        
    - name: Install dependencies
      run: npm install
      
    - name: Deploy to Production
      run: |
        echo "Deploying version ${{ inputs.version }} to production environment..."
        echo "Application deployed to production"